### PR TITLE
Added russian localization

### PR DESCRIPTION
**Pull request by l-e-s**

### CODE REVIEW

**Review by ildyria — APPROVED** [review]
Looks good to me.

**Comment by ildyria** [comment]
@l-e-s could you also make the same PR for https://github.com/LycheeOrg/Lychee-Laravel/

The localization is very similar, see here https://github.com/LycheeOrg/Lychee-Laravel/tree/master/app/Locale

You will also be able to do `make test` to see if you are missing entries. :)
(We do not have a test suite on the v3)

**Comment by l-e-s** [comment]
Now i'm trying to install lychee-laravel on my server. It's not so easy because it should work at subfolder... still working on PHP-FPM configuration.

**Comment by ildyria** [comment]
I assume you are using nginx.
Have a look at that one: https://github.com/LycheeOrg/Lychee-Laravel/issues/349

**Comment by l-e-s** [comment]
That's it! Thank you very much! I'll try to make a PR ASAP.

**Pull request merged**
