### PR TITLE
Slightly improve lens info by using LensSpec tag instead of Lens tag

### LINKED ISSUE #234: Show complete Lens name in About Photo
### Detailed description of the problem
Instead of, for example, `24mm f/1.8`, it should show `AF-S Nikkor 24mm f/1.8G ED` (_ExifTool -LensID tag_) when using system ExifTool. 

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Error: Upgrade to PHP 7.1 or higher


System Information
------------------
Lychee Version (json):  3.2.13
DB Version:             update_030213
System:                 Linux
PHP Version:            7
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             2.2.4
Plugins:                


Config Information
------------------
version:                 update_030213
checkForUpdates:         1
sortingPhotos:           ORDER BY id DESC
sortingAlbums:           ORDER BY id DESC
imagick:                 1
lang:                    en
skipDuplicates:          0
layout:                  0
image_overlay:           1
default_license:         reserved
small_max_width:         0
small_max_height:        360
medium_max_width:        1920
medium_max_height:       1080
deleteImported:          1
image_overlay_type:      desc
php_script_limit:        0
useExiftool:             1
```

### Browser and system
Firefox 66, x86_64 Linux

### PR DESCRIPTION
**Pull request by mir07**
Fixes #234

Signed-off-by: Michael Rasmussen <mir@datanom.net>

### CODE REVIEW

**Comment by d7415** [comment]
As there's already a hierarchy here, I'd just add any new tags to the list rather than replacing them. I'm not sure how likely it is for exiftool to return `Lens` but not `LensSpec` but if it's possible we should account for it. This would also allow us to include `LensID` in the list, as requested.

`LensID` isn't an official EXIF tag, but looks like it's a combination of others so I guess it's probably ok (as we're officially supporting `exiftool` anyway)

**Review by d7415 — CHANGES_REQUESTED** [review]
As there's already a hierarchy here, I'd just add any new tags to the list rather than replacing them. I'm not sure how likely it is for exiftool to return Lens but not LensSpec but if it's possible we should account for it. This would also allow us to include LensID in the list, as requested.

LensID isn't an official EXIF tag, but looks like it's a combination of others so I guess it's probably ok (as we're officially supporting exiftool anyway)

**Comment by d7415** [comment]
(I've added a reference to the issue in the description above so that it can be automatically closed on merge)

**Comment by mir07** [comment]
I have come to the same conclusion so I will prepare a patch to handle all possible lens info tags ordering from best to worst so:
1) LensID
2) LensSpec
3) Lens

**Comment by ildyria** [comment]
Also if such thing can also be added to Lychee-Laravel that would be nice. https://github.com/LycheeOrg/Lychee-laravel

**Comment by mir07** [comment]
I know but I have never been able to have a functioning Lychee-Laravel installation even when following the instructions to the letter. Without a functioning Lychee-Laravel installation providing patches is impossible.

**Comment by d7415** [comment]
Thanks @mir07 !

**Pull request closed without merging**
