### PR TITLE
Fix for https

### PR DESCRIPTION
**Pull request by roblandry**
I use https and the links were improperly formed. This should correct for both https and http.

### CODE REVIEW

**Comment by d7415** [comment]
This seems quite heavy-handed. Additionally, it should be part of #181 rather than its own PR.

**Comment by d7415** [comment]
You should be able to update the PR by pushing this commit to the `sharing_meta` branch on your fork.

**Comment by d7415** [comment]
My bad. It certainly could be combined but wasn't dependent like I first thought.

I'd be tempted to just default to https, but I'm going to have to take a closer look at what that does. Sorry for the noise.

**Comment by d7415** [comment]
Ok. I looked again. I don't think this does what you think it does. Unless someone else has some insight I'm going to close this again.

In short, the `http://` appears to be a dummy value to keep `parse_url` happy. The scheme component of this is never used, and the URLs are output in the format `//example.com/index.php` which will keep the scheme currently in use.

**Comment by roblandry** [comment]
Ahh... when looking at the links without this, i just saw "//:the url stuff" and wanted to make it display properly. Didnt realise it was performing magic. :-)

**Comment by d7415** [comment]
Easily done!

**Pull request closed without merging**
