### PR TITLE
Add Portuguese language translation

### PR DESCRIPTION
**Pull request by hsousa**
Copied `English.php` and translated all strings to Portuguese.

Let me know if there's anything else needed to have this available in my native language.

### CODE REVIEW

**Comment by tmp-hallenser** [comment]
Thanks @hsousa 
We're moving to Lychee v4 based on Laravel and Lychee v3 (this repo) will at some point not maintained any more. Would you be willing to also translate the language files to Portuguese for Lychee v4? (https://github.com/LycheeOrg/Lychee-Laravel/tree/ce689ab60e6ab52aa65c1dc0d5ed3c2a7e87b402/app/Locale)

**Comment by hsousa** [comment]
Sure! I didn't even know this was happening.

I'm using Lychee with a Docker container on Unraid. Any easy way to give v4 a spin that way?

**Comment by d7415** [comment]
> I'm using Lychee with a Docker container on Unraid. Any easy way to give v4 a spin that way?

There's [Lychee-Laravel-Docker](https://github.com/LycheeOrg/Lychee-Laravel-Docker)

**Comment by hsousa** [comment]
Right, I noticed after following the URL... 😅 

No problem, I'll add a Portuguese translation there too soon!

**Pull request merged**
