### PR TITLE
Updated translation for v3.2.8, fixes, spell check

### PR DESCRIPTION
**Pull request by anroth76**
Updated German locale for Lychee v3.2.8, synced line numbers with English.php, fixed/improved some expressions, spelling and punctuation.

### CODE REVIEW

**Comment by ildyria** [comment]
Thank you for your PR. :+1:  :)

Could you please use tabs instead of space for indentation ? :s

**Review by ildyria — CHANGES_REQUESTED** [review]
Also you are missing some lines from https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/lychee_locale.js
I forgot to add them in English.php. Will do soon (sorry for that).

**Comment by anroth76** [comment]
> Thank you for your PR. 👍 :)
> 
> Could you please use tabs instead of space for indentation ? :s

I copied the code from my local copy in Notepad++, apparently, my browser might have screwed up something (I'm all new to GitHub). I noticed that some stuff is missing, like the labels for the buttons in the upper right corner, will check the lychee_locale.js if I can find those. :)

**Comment by ildyria** [comment]
>  like the labels for the buttons in the upper right corner

Yeah that is something we cannot change in the current version of Lychee (v3). The next version should be able solve this (available at your own risk here: https://github.com/ildyria/Lychee-Laravel ).

Fortunately we just need to copy paste the `lang` folder. :)
However the label have not been translated yet. :|

**Review by ildyria — APPROVED** [review]

**Comment by anroth76** [comment]
Aw man, just when you think you got everything... I found another typo in line 323: "Foto-Manaagement" should be "Foto-Management", naturally. Maybe it's quicker if you fix it in the master files yourself?

**Comment by d7415** [comment]
> Aw man, just when you think you got everything... I found another typo in line 323: "Foto-Manaagement" should be "Foto-Management", naturally. Maybe it's quicker if you fix it in the master files yourself?

On it...

**Comment by d7415** [comment]
Done

**Pull request merged**
