### PR TITLE
Feature: Album sorting by takestamp

### PR DESCRIPTION
**Pull request by elias-fauser**
I implemented an sorting option to sort the albums by the lastest/ oldest takestamp of its contained photos. 

lychee_03108
lychee_03108_sorting_dialog

This is achieved by:
- Adding a `min_takestamp` and `max_takestamp` fields as int(11) in `lychee_albums`
- Changing all functions which alter photos to save the updated takestamp to the appropriate album entry: Add Photos, Delete Photos, Merge Albums, Move Photo
- Extended the settings data: prepareData(), setSortingAlbums()
- Changed the javascript code to use the takestamps if the takestamp sorting is used (otherwise the sysstamp is used)  
- compiled the dist folder to match the changes

I added this as version 3.1.8 with the respective update file.

### CODE REVIEW

**Comment by elias-fauser** [comment]
I found one issue in the update file where there was a missing predicate in the SQL query. It was fixed in the lastest commit

**Comment by ildyria** [comment]
@elias-fauser Could you squash your pull request so we can have a clean diff between the current master version and your PR? This would help the review a lot.

**Comment by elias-fauser** [comment]
@ildyria I squashed my commits. Hope that helps

**Comment by ildyria** [comment]
@elias-fauser Thanks I'll have a look tomorrow or this weekend. :)

**Comment by ildyria** [comment]
I cherry-picked the last commit and merged it in the master branch.
Thanks. :)

**Pull request closed without merging**
