### PR TITLE
Ensure that max height is respected with GD

### LINKED ISSUE #196: Medium image height can be wrong with GD
### Detailed description of the problem
For pictures with a ratio smaller than 16:9, when using GD, the height of the generated medium picture can exceed the default 1080.

### Steps to reproduce the issue
Make sure that imagick is not being used.
Add a new picture with the resolution of 4608x3456 (4:3 aspect ratio).
Check the resolution of the generated medium picture: it will be 1920x1440 instead of the expected 1440x1080.

### Output of the diagnostics (Settings => Diagnostics)
Lychee Version (json):  3.2.12
DB Version:             update_030212
System:                 Linux
PHP Version:            7.2
MySQL Version:          50724
Imagick:                -
Imagick Active:         0
Imagick Version:        -
GD Version:             bundled (2.1.0 compatible)
Plugins:                

### Browser and system
Firefox 64.0.2 on Linux

### PR DESCRIPTION
**Pull request by kamil4**
Fixes #196

### CODE REVIEW

**Comment by kamil4** [comment]
Sorry, only the 7fcf421 commit is relevant to this issue, the 19d98ce one is unrelated (I still need to learn how to deal with git submodules properly).

**Comment by ildyria** [comment]
@kamil4 The best way to do a PR is as follow:
```
# fork the repo Lychee AND Lychee-front
git clone git@github.com:username/Lychee.git
git submodule init
git submodule update
git checkout -b new_thing_you_want_to_add
# modify
git add # the thing you modified
git commit -m #blabla the thing you modified
git push origin new_thing_you_want_to_add
```
and then create a PR.

You can then `git checkout master` to go back to master and do more changes.
In such way you ensure that the changes you make to your master does not polutes the PR you made. :)

**Review by ildyria — APPROVED** [review]
I did not test this, but this looks okay to me.

**Comment by ildyria** [comment]
Merged via #202

**Comment by kamil4** [comment]
@ildyria, one more question about submodules:
`git submodule init`
clones the Lychee-front submodule from LycheeOrg/Lychee-front.git, not from my forked version. Can I still make changes to that version of Lychee-front or should I use a separate directory tree for that, just with a clone of my forked Lychee-front?

**Comment by ildyria** [comment]
https://stackoverflow.com/questions/913701/how-to-change-the-remote-repository-for-a-git-submodule

> You should just be able to edit the `.gitmodules` file to update the URL and then run `git submodule sync` to reflect that change to the superproject and your working copy.

**Comment by ildyria** [comment]
Your submodule is just another git repo. The same steps for adding an additional remote and pushing the changes apply here as well.

Also you can simply do:
```
cd Lychee-front
git remote add fork git@github.com:kamil4/Lychee-front.git
git fetch fork
```
and you just need to push to `fork`.

The sequence to make a PR to Lychee (if you modify Lychee-Front) is slightly different though.
You need to first make a PR for Lychee-front, to wait for it to merge and then make a PR to Lychee with the correct Lychee-front setting.

**Pull request closed without merging**
